title: My GitHub Pages Site
description: A simple Jekyll site hosted on GitHub Pages
baseurl: "" # Leave empty if using user or organization pages
url: "https://engineerkhan.github.io" # Replace with your GitHub username
